tuto/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|


Route::get('/', function () {
    return view('welcome');
});*/

//Esta es la primera prueba de ruta que se hace en el tutorial 3, solo regresa un string
Route::get('regresa_string', function () {
    return "Hello World";
});

//Esta es la segunda prueba que regresa una vista
Route::get('regresa_vista', function () {
    return view('paginas.prueba1');
});

/*
La parte numero 3 del tutorial pide que creemos
3 rutas diferentes para 3 vistas diferentes
*/
/*
Route::get('acerca', function () {
    return view('paginas.acerca');
});
Route::get('contacto', function () {
    return view('paginas.contacto');
});
Route::get('ayuda', function () {
    return view('paginas.ayuda');
});

*/

/*
La parte numero 4 del tutorial pide que creemos
rutas "compuestas"
*/
Route::get('primero/segundo', function () {
    return view('paginas.prueba1');
});



/* Tutorial #4

  Nos pide que utilicemos los named routes

  */

  Route::get('acerca', [
      'as' => 'acerca',
      'uses' => 'ControladorPaginas@getAcerca'
  ]);

  Route::get('contacto', [
      'as' => 'contacto',
      'uses' => 'ControladorPaginas@getContacto'
  ]);

  Route::get('ayuda', [
      'as' => 'ayuda',
      'uses' => 'ControladorPaginas@getAyuda'
  ]);

  Route::get('/', [
      'as' => '/',
      'uses' => 'ControladorPaginas@getIndex'
  ]);


  Route::resource('producto', 'ControladorProducto');

//PARTE 1 de TUTORIAL

/*
  Route::get('basicrouting', function(){
    return "This is basic routing.";
  });
*/
Route::get('basicrouting', function(){
  return view('welcome');
});


Route::match(['get','post','delete'],'matchrouting',function(){
  return 'matchrouting';
  //return view('welcome');
});
Route::any('anyroute',function(){
  return 'anyroute';
});

Route::group(['as'=>'admin::'],function(){
  Route::get('dashboard', [
    'as' => 'dashboard',
    'uses' => 'PagesController@getIndex'
  ]);
  Route::get('reports', [
    'as' => 'namedRoutes',
    'uses' => 'PagesController@getIndex'
  ]);
});

Route::get('user/{id}',function($id){
  //$user = User::find($id);

  return $id;
  //return view('welcome');
})
->where('id','[0-9]+');
Route::get('namedRoutes', [
  'as' => 'namedRoutes',
  'uses' => 'PagesController@getIndex'
]);
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

tuto/app/Producto.php
<?php

/*
  RECUERDA QUE EN LA BASE DE DATOS SE ESCRIBE EL NOMBRE DEL "OBJETO" EN MINUSCULAS Y EN PLURAL

  EN ESTE CASO LA TABLA DE Producto SE LLAMA productos

*/

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    //ESTA LINEA ES LA QUE DICE LA TABLA QUE SE VA A UTILIZAR EN CASO DE NO CUMPLIR CON LO ANTERIOR
    protected $table='productos';
    public $timestamps = false;
    protected $fillable = ['nombre','precio'];
}

tuto/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

tuto/app/Http/Controllers/ControladorPaginas.php
<?php

namespace App\Http\Controllers;


use App\Http\Controllers\Controller;

class ControladorPaginas extends Controller
{
  public function getAcerca(){
    //Le vamos a pasar como variable el nombre de la compañia
    $nombre_comp = "HCDESARROLLO";
    $estaregistrado = false;

    $lista_nombres = array("Hugo", "Carla", "Armando", "Alex");
    return view('paginas.acerca')
      ->with("nombre", $nombre_comp)
      ->with("estaregistrado", $estaregistrado)
      ->with("usuarios", $lista_nombres);
  }

  public function getContacto(){
    return view('paginas.contacto');
  }

  public function getAyuda(){
    return view('paginas.ayuda');
  }

  public function getIndex(){
    return view('welcome');
  }
}

tuto/app/Http/Controllers/ControladorProducto.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Producto;

class ControladorProducto extends Controller
{
    //
    public function index(){
      $productos = Producto::all();
      /*
      return $productos;
      return "LA PAGINA DE PRODUCTO";
      */

      return view('productos.index')->with('lista_productos',$productos);
    }

    public function create(){
      return view('productos.crear');
    }

    public function store(Request $request){
      /*
      $product = new Producto;
      $product->nombre= $request->nombre;
      $product->precio= $request->precio;
      $product->save();*/

      $inputs = $request->all();
      $producto=Producto::Create($inputs);
      return redirect()->route('producto.index');

    }

    public function show($id){
      $product = Producto::find($id);
      //return $product;
      return view('productos.show')->with('producto',$product);
    }

    public function destroy ($id){
      Producto::destroy($id);
      $productos = Producto::all();
      return redirect()->route('producto.index');
    }


    public function edit($id){
      $product = Producto::find($id);
      return view('productos.edit')->with('producto',$product);
    }

    public function update(Request $request, $id){
      $product = Producto::find($id);
      $product->nombre=$request->nombre;
      $product->precio=$request->precio;

      $product->save();

      return redirect()->route('producto.index');
    }
}

tuto/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

tuto/resources/views/layouts/layout_gen.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> @yield('title') </title>
  </head>

  <body>
    @include('layouts.menu')
    @yield('body')
  </body>

</html>

tuto/resources/views/layouts/menu.blade.php
<ul>
  <li> Inicio </li>
  <li> Login </li>
  <li> Acerca de nosotros </li>
  <li> Contacto </li>
</ul>

tuto/resources/views/paginas/acerca.blade.php
@extends('layouts.layout_gen')


@section('title')
  Acerca de Nosotros
@stop

@section('body')
  <h1>Esta es la Pagina de ACERCA DE NOSOTROS </h1>

  <p>Mi compañia es : {{$nombre}}</p>
  @if($estaregistrado==true)
    <p>Hola compi</p>
  @else
    <p>Porfa ingresa a la pagina</p>
  @endif
  @for ($i = 0; $i < 10; $i++)
    <p>The current value is {{ $i }}</p>
  @endfor

  <h3>Nuestro equipo es : </h3>
  <ul>
    @foreach ($usuarios as $usuario)
      <li>{{ $usuario }}</li>
    @endforeach
  </ul>
@stop

tuto/resources/views/paginas/ayuda.blade.php
Esta es la Pagina de AYUDA

tuto/resources/views/paginas/contacto.blade.php
@extends('layouts.layout_gen')


@section('title')
  Contacto
@stop

@section('body')
  <h1>Esta es la pagina de CONTACTO</h1>

  <input type="text" name="nombre" placeholder="nombre producto">
  <input type="text" name="precio" placeholder="Precio producto">
@stop

tuto/resources/views/paginas/prueba1.blade.php
<?/*
  ESTA ES LA SEGUNDA PRUEBA QUE PIDE EL TUTORIAL,
  BUSCA QUE SE REGRESE ESTA VISTA EN LUGAR DE UN STRING
*/
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title">Prueba de Regreso de vista</div>
            </div>
        </div>
    </body>
</html>

tuto/resources/views/productos/crear.blade.php
@extends('layouts.layout_gen')

@section('title')
  Crear Producto
@stop


@section('body')
  <h1> CREA UN NUEVO PRODUCTO</h1>
  <form method="POST" action="{{route('producto.store')}}">
    <input type="text" name="nombre">
    <input type="text" name="precio">
    <input type="submit">
  </form>

@stop

tuto/resources/views/productos/edit.blade.php
@extends('layouts.layout_gen')

@section('title')

Editar {{$producto->nombre}}

@stop


@section('body')
  <h1> Edita Producto {{$producto->nombre}}</h1>
  <form method="POST" action="{{route('producto.update',$producto->id)}}">
    <input type="text" name="nombre" value="{{$producto->nombre}}">
    <input type="text" name="precio" value="{{$producto->precio}}">
    <input type="submit" value="Editar">
    {{ method_field('PATCH') }}
  </form>

@stop

tuto/resources/views/productos/index.blade.php
@extends('layouts.layout_gen')

@section('title')

TODOS LOS PRODUCTOS

@stop


@section('body')

  <a href="{{route('producto.create')}}"> CREAR </a>

  @foreach($lista_productos as $producto)
    <h1>{{$producto->nombre}}</h1>
    <h3>{{$producto->precio}}</h3>
    <hr>
  @endforeach
  <a href="{{url('basicrouting')}}">Basic routing</a>
<a href="{{route('product.create')}}">Create</a>
@stop

tuto/resources/views/productos/show.blade.php
@extends('layouts.layout_gen')

@section('title')

{{$producto->nombre}}

@stop


@section('body')

  <h1>{{$producto->nombre}}</h1>
  <h3>{{$producto->precio}}</h3>
  <form method="POST" action="{{route('producto.destroy', $producto->id)}}">
    <a href="{{route('producto.edit', $producto->id)}}">edit</a>
    <input type="submit" value="delete">
    {{ method_field('DELETE') }}
  </form>
@stop